bulklot/urls.py
from django.urls import path

from . import views

app_name = 'bulklot'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('lotreq/', views.LotReqList.as_view(), name='lot_req_list'),
    path('lotreq/form', views.LotReqCreate.as_view(), name='lot_req_create'),
    path('lotreq/<int:pk>', views.LotReqDetail.as_view(), name='lot_req_detail'),
    path('member/', views.MemberList.as_view(), name='member_list'),
    path('member/form', views.MemberCreate.as_view(), name='member_create'),
    path('member/<int:pk>', views.MemberUpdate.as_view(), name='member_update'),
    path('member/<int:pk>/delete', views.MemberDelete.as_view(), name='member_delete'),
    path('lotresult/', views.LotResultList.as_view(), name='lot_result_list'),
]

llamapaca/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('registration.urls')),
    path('django-rq/', include('django_rq.urls')),
    path('bulklot/', include('bulklot.urls')),
    path('admin/', admin.site.urls),
]

bulklot/models.py
from django.db import models
from django.contrib.auth.models import User

class LotRequest(models.Model):
    requester = models.ForeignKey(User, verbose_name="申込者", on_delete=models.CASCADE)
    req_date = models.DateTimeField(verbose_name="申込日", auto_now_add=True)
    location = models.CharField(
                   verbose_name="場所", 
                   max_length=100,
                   choices=[('10,2', '舎人公園'),], # offset,item
                   blank=False,
                   default='舎人公園',
               )
    sport = models.CharField(
                verbose_name="種目", 
                max_length=100,
                choices=[('130', 'テニス（人工芝）'),],
                blank=False,
                default='テニス（人工芝）',
            )

    def __str__(self):
        return self.req_date.strftime('%Y年%-m月%-d日%H:%M') + '/' + \
               self.requester.username + '/' + \
               self.get_location_display() + '/' + \
               self.get_sport_display()

class Member(models.Model):
    owner = models.ForeignKey(User, verbose_name="所有者", on_delete=models.CASCADE)
    name = models.CharField(verbose_name="名前", max_length=100, blank=False)
    tmgbc_id = models.CharField(verbose_name="TMGBC登録番号", max_length=8, blank=False)
    tmgbc_password = models.CharField(verbose_name="TMGBCパスワード", max_length=15, blank=False)

    def __str__(self):
        return self.name

class LotRequestTime(models.Model):
    lot_request = models.ForeignKey(LotRequest, verbose_name="抽選申込", on_delete=models.CASCADE)
    member = models.ForeignKey(Member, verbose_name="メンバー", on_delete=models.SET_NULL, blank=False, null=True)
    date = models.DateField(verbose_name="日付")
    time = models.CharField(
               verbose_name="時間帯",
               max_length=40,
               choices=[
                   ('900_1100','09:00～'),
                   ('1100_1300','11:00～'),
                   ('1300_1500','13:00～'),
                   ('1500_1700','15:00～'),
                   ('1700_1900','17:00～'),
               ]
           )
    status = models.CharField(
                verbose_name="ステータス", 
                max_length=40,
                choices=[
                    ('10','待機中'),
                    ('20','処理中'),
                    ('30','完了'),
                    ('40','エラー'),
                ],
                blank=False,
                default='10',
            )

    def __str__(self):
        return self.lot_request.__str__() + '/' + \
               self.member.name + '/' + \
               self.date.strftime('%Y年%-m月%-d日') + '/' + \
               self.get_time_display() + '/' + \
               self.get_status_display()

class LotResult(models.Model):
    owner = models.ForeignKey(
                User, 
                verbose_name="所有者", 
                on_delete=models.CASCADE
            )
    member = models.ForeignKey(
                 Member, verbose_name="メンバー", 
                 on_delete=models.SET_NULL, 
                 blank=False, 
                 null=True,
             )
    datetime = models.CharField(
                   verbose_name="希望日時",
                   max_length=100,
               )
    sport = models.CharField(
                verbose_name="種目", 
                max_length=100,
            )
    location = models.CharField(
                   verbose_name="公園名", 
                   max_length=100,
               )
    result = models.CharField(
                 verbose_name="抽選結果", 
                 max_length=40,
             )
    pubdate = models.DateField(
                  verbose_name="取得日"
              )
    active = models.BooleanField(
                 default=True,
             )

    def __str__(self):
        return self.member.name + '/' + \
               self.datetime + '/' + \
               self.sport + '/' + \
               self.location + '/' + \
               self.result + '/' + \
               self.pubdate.strftime('%Y年%-m月%-d日') + '/' + \
               str(self.active)

bulklot/forms.py
from django.forms import inlineformset_factory, DateInput
from .models import LotRequest, LotRequestTime

def lotReqTimeFormSet_factory(extra=0):
    return inlineformset_factory( 
        LotRequest, 
        LotRequestTime,
        fields=['member', 'date', 'time'],
        can_delete=False,
        widgets={'date': DateInput(attrs={"type":"date"})},
        extra=extra,
        min_num=1,
        validate_min=True,
        )

bulklot/views.py
import datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import LotRequest, LotRequestTime, Member, LotResult
from .forms import lotReqTimeFormSet_factory
from .utils import login_to_tmgbc

class Index(LoginRequiredMixin, generic.base.TemplateView):
    template_name = 'bulklot/index.html'

class LotReqList(LoginRequiredMixin, generic.ListView):
    model = LotRequest

    def get_queryset(self):
        return LotRequest.objects.filter(requester=self.request.user).order_by('-req_date')

class LotReqDetail(LoginRequiredMixin, generic.DetailView):
    model = LotRequest

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lotreqtime_list'] = self.object.lotrequesttime_set.order_by('id')
        return context

class LotReqCreate(LoginRequiredMixin, generic.CreateView):
    model = LotRequest
    fields = ['sport', 'location']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            LotReqTimeFormSet = lotReqTimeFormSet_factory()
            context['lotreqtime_formset'] = LotReqTimeFormSet(self.request.POST)
        else:
            # 自分のメンバーの人数×2のLotReqTimeフォームを用意する
            initial = []
            members = Member.objects.filter(owner=self.request.user) 
            amonthago = datetime.date.today() + datetime.timedelta(days=31)
            date = datetime.date(amonthago.year, amonthago.month, 1)
            for member in members:
                initial += [{'member': member, 'date': date, 'time': '1300_1500'}]
                initial += [{'member': member, 'date': date, 'time': '1300_1500'}]
            LotReqTimeFormSet = lotReqTimeFormSet_factory(len(initial)-1)
            lrtfs = LotReqTimeFormSet(initial=initial)

            # 自分のメンバーしか選べなくする
            for lrtf in lrtfs.forms:
                lrtf.fields['member'].queryset = members

            context['lotreqtime_formset'] = lrtfs
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        lotReqTimeFormSet = context['lotreqtime_formset'];

        if form.is_valid() and lotReqTimeFormSet.is_valid():
            form.instance.requester = self.request.user
            self.object = form.save()
            lotReqTimeFormSet.instance = self.object
            lotReqTimes = lotReqTimeFormSet.save()
    
            # フォームの入力値を取得
            sport = self.request.POST.get('sport')
            location = self.request.POST.get('location').split(',')
            location_page = location[0]
            location_id = location[1] 

            # 1つずつ抽選申込を実行
            for lotReqTime in lotReqTimes:
                print(lotReqTime)
                # 非同期で抽選申込を実行
                login_to_tmgbc.delay(sport, location_page, location_id, lotReqTime)

        else:
            return self.form_invalid(form)
    
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('bulklot:lot_req_detail', kwargs={'pk': self.object.pk})

class MemberList(LoginRequiredMixin, generic.ListView):
    model = Member

    def get_queryset(self):
        return Member.objects.filter(owner=self.request.user)

class MemberCreate(LoginRequiredMixin, generic.CreateView):
    model = Member
    fields = ['name', 'tmgbc_id', 'tmgbc_password']
    success_url = reverse_lazy('bulklot:member_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class MemberUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Member
    fields = ['name', 'tmgbc_id', 'tmgbc_password']
    success_url = reverse_lazy('bulklot:member_list')

class MemberDelete(LoginRequiredMixin, generic.DeleteView):
    model = Member
    fields = ['name', 'tmgbc_id', 'tmgbc_password']
    success_url = reverse_lazy('bulklot:member_list')

class LotResultList(LoginRequiredMixin, generic.ListView):
    model = LotResult

    def get_queryset(self):
        return LotResult.objects.filter(owner=self.request.user, active=True).order_by('member', 'datetime')

bulklot/templates/bulklot/base.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% block bootstrap4_title %}{% block title %}{% endblock %} | 一括抽選{% endblock %}

{% block bootstrap4_content %}

<div class="container">
	<a href="{% url 'bulklot:index' %}" class="text-reset text-decoration-none">
		<h1>TMGBC一括抽選</h1>
	</a>
	{% if user.is_authenticated %}
	        <div class="text-right">ユーザー: {{user}}</div>
	{% endif %}
	{% block contents %}{% endblock %}
</div>

<br><br>

{% endblock %}

bulklot/templates/bulklot/index.html
{% extends 'bulklot/base.html' %}

{% block title %}ホーム{% endblock %}

{% block contents %}

<h2>ホーム</h2>

<a href="{% url 'bulklot:lot_req_list' %}" class="btn btn-primary btn-lg btn-block">抽選申込</a>
<a href="{% url 'bulklot:member_list' %}" class="btn btn-primary btn-lg btn-block">メンバー</a>
<a href="{% url 'bulklot:lot_result_list' %}" class="btn btn-primary btn-lg btn-block">抽選結果</a>
<br>
<a href="{% url 'registration:logout' %}" >ログアウト</a>

{% endblock %}

bulklot/templates/bulklot/lotrequest_detail.html
{% extends 'bulklot/base.html' %}

{% block title %}申込詳細{% endblock %}

{% block contents %}

<h2>申込詳細</h2>

<p>申込日：{{ lotrequest.req_date | date:"Y/m/d(D) H:i:s" }}</p>
<p>種目：{{ lotrequest.get_sport_display }}</p>
<p>場所：{{ lotrequest.get_location_display }}</p>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">メンバー</th>
        <th scope="col">日時</th>
        <th scope="col">ステータス</th>
      </tr>
    </thead>
    <tbody>
      {% for lotreqtime in lotreqtime_list %}
      <tr>
        <td>{{ lotreqtime.member }}</td>
        <td>{{ lotreqtime.date | date:"m/d(D)" }} {{ lotreqtime.get_time_display }}</td>
        <td id='{{ lotreqtime.id }}-status'>{{ lotreqtime.get_status_display }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


<a href="{% url 'bulklot:lot_req_list' %}">一覧へ戻る</a>

{% endblock %}

bulklot/templates/bulklot/lotrequest_form.html
{% extends 'bulklot/base.html' %}
{% load bootstrap4 %}

{% block title %}申込フォーム{% endblock %}

{% block contents %}

<h2>申込フォーム</h2>

{% bootstrap_form_errors form %}
{% bootstrap_formset_errors lotreqtime_formset %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {{ lotreqtime_formset.management_form }}

    {% for lotreqtime in lotreqtime_formset %}
        <div class="card bg-light mb-3">
        <div class="card-body">
        <div class="row">
	    {% bootstrap_form lotreqtime form_group_class='form-group col-lg' layout='horizontal' %}
	</div>
	</div>
	</div>
    {% endfor %}

    {% bootstrap_button "申込" %}
</form>

<br>

<a href="{% url 'bulklot:lot_req_list' %}">一覧へ戻る</a>

{% endblock %}

bulklot/templates/bulklot/lotrequest_list.html
{% extends 'bulklot/base.html' %}

{% block title %}申込履歴{% endblock %}

{% block contents %}

<h2>申込履歴</h2>
<a href="{% url 'bulklot:lot_req_create' %}" class="btn btn-primary">新規抽選申込</a>
<a href="{% url 'bulklot:member_list' %}" class="btn btn-primary">メンバー</a>

<br><br>

<table class="table">
    <thead>
        <tr>
            <th scope="col">申込日時</th>
            <th scope="col">種目</th>
            <th scope="col">場所</th>
        </tr>
    </thead>
    <tbody>
        {% for req in lotrequest_list %}
        <tr>
            <td>
                <a href="{% url 'bulklot:lot_req_detail' req.id %}">
                {{ req.req_date | date:"Y/m/d(D) H:i:s" }}</a>
            </td>
            <td>{{ req.get_sport_display }}</td>
            <td>{{ req.get_location_display }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{% url 'bulklot:index' %}">ホームへ戻る</a>

{% endblock %}

bulklot/templates/bulklot/lotresult_list.html
{% extends 'bulklot/base.html' %}

{% block title %}抽選結果{% endblock %}

{% block contents %}

<h2>抽選結果</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col">メンバー</th>
	    <th scope="col">希望日時</th>
	    <th scope="col">結果</th>
        </tr>
    </thead>
    <tbody>
        {% for result in lotresult_list %}
        <tr>
	    <td>{{ result.member }}</a></td>
            <td>{{ result.datetime }}</td>
            <td>{{ result.result }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{% url 'bulklot:index' %}">ホームへ戻る</a>

{% endblock %}

bulklot/templates/bulklot/member_confirm_delete.html
{% extends 'bulklot/base.html' %}
{% load bootstrap4 %}

{% block title %}メンバー削除{% endblock %}

{% block contents %}

<h2>メンバー削除</h2>

<form method="post">
    {% csrf_token %}
    <p>"{{ object }}"を削除してよろしいですか？</p>
    {% bootstrap_button "削除" button_class='btn-danger' %}
    <a href="{% url 'bulklot:member_update' object.id %}" class="btn btn-secondary">キャンセル</a>
</form>

<br>


{% endblock %}

bulklot/templates/bulklot/member_form.html
{% extends 'bulklot/base.html' %}
{% load bootstrap4 %}

{% block title %}メンバー登録フォーム{% endblock %}

{% block contents %}

<h2>メンバー登録フォーム</h2>

{% bootstrap_form_errors form %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% if object %}
        {% bootstrap_button "変更" %}
        <a href="{% url 'bulklot:member_delete' object.id %}" class="btn btn-danger">削除</a>
    {% else %}
        {% bootstrap_button "登録" %}
    {% endif %}
</form>

<br>

<a href="{% url 'bulklot:member_list' %}">一覧へ戻る</a>


{% endblock %}

bulklot/templates/bulklot/member_list.html
{% extends 'bulklot/base.html' %}

{% block title %}メンバー{% endblock %}

{% block contents %}

<h2>メンバー</h2>
<a href="{% url 'bulklot:member_create' %}" class="btn btn-primary">新規メンバー登録</a>
<a href="{% url 'bulklot:lot_req_list' %}" class="btn btn-primary">抽選申込</a>

<br><br>

<table class="table">
    <thead>
        <tr>
            <th scope="col">名前</th>
	    <th scope="col">TMGBC<br>登録番号</th>
	    <th scope="col">TMGBC<br>パスワード</th>
        </tr>
    </thead>
    <tbody>
        {% for member in member_list %}
        <tr>
	    <td><a href="{% url 'bulklot:member_update' member.id %}">{{ member.name }}</a></td>
            <td>{{ member.tmgbc_id }}</td>
            <td>{{ member.tmgbc_password }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{% url 'bulklot:index' %}">ホームへ戻る</a>

{% endblock %}